config/routes.rb
EveAlert::Application.routes.draw do
  match 'user' => 'user#index', :as => :home
  resources :accounts do
      resources :characters
  end

  resources :events

  match '/' => 'welcome#index'
end

app/models/account.rb
class Account < ActiveRecord::Base
  include EveRecord

  belongs_to :user
  has_many :characters, :dependent => :destroy

  validate :must_have_full_api_key
  after_save :get_characters

  def api
    @api ||= Reve::API.new(self.id, self.full_api_key)
  end

  def refresh
    self.characters.each do |c|
      c.refresh
    end
  end

  def must_have_full_api_key
    character = api.characters.first
    api.personal_wallet_balance( :characterid => character.id )
  rescue Reve::Exceptions::ReveError => e
    errors.add_to_base("Eve API: " + e.to_s)
  end

  def get_characters
    if_stale(self.id, self.api.characters_url, {}, 1.hour) do
      self.characters.clear
      begin
        api.characters.each do |x|
          self.characters.create(x.instance_values)
        end
      rescue Exception => e
        self.error = "Error: " + e.to_s
      else
        self.error = nil
      ensure
        self.send(:create_or_update_without_callbacks)
      end
    end
    self.characters
  end
end

app/controllers/accounts_controller.rb
class AccountsController < SecureController
  
  # GET /accounts
  # GET /accounts.xml
  def index
    redirect_to home_url
    # @accounts = current_user.accounts
    # 
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml  { render :xml => @accounts }
    # end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = current_user.accounts.build(params[:account])

    respond_to do |format|
      if @account.save
        flash[:notice] = 'Account was successfully created.'
        format.html { redirect_to(home_url) }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        flash[:notice] = 'Account was successfully updated.'
        format.html { redirect_to(home_url) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(home_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_accounts.html.erb
<div id="accounts">
  <h2>Eve Accounts</h2>
  <ul>
    <% accounts.each do |account| %>
    <li><%=h account.id %> &mdash; 
      <% if account.error %>
        <span class="error_message"><%=h account.error %></span>
      <% else %>
      <span id="character_names"><%=h account.characters.map{|x| x.name}.join(", ") %></span>
      <% end %>
      [<%= link_to "edit", edit_account_path(account) %>]
    </li>
    <% end -%>
  </ul>
  <p><%= link_to "Add an account", new_account_path %></p>
</div>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<% form_for(@account) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :id %><br />
    <%= f.text_field :id, {:size => 8} %>
  </p>
  <p>
    <%= f.label :full_api_key %><br />
    <%= f.text_field :full_api_key, {:size => 65} %>
  </p>
  <p>
    <%= f.submit 'Update' %> | 
    <%= link_to 'Cancel', home_path %> | 
    <%= link_to 'Remove', @account, :confirm => 'Are you sure?', :method => :delete %>
  </p>
  <p>
    You can find your Eve API keys at 
    <%= link_to "http://www.eveonline.com/api/default.asp", "http://www.eveonline.com/api/default.asp" %>.
  </p>
<% end %>

app/views/accounts/index.html.erb
<%= render :partial => 'accounts/accounts.html.erb', :locals => {:accounts => @accounts} %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<% form_for(@account) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :id %><br />
    <%= f.text_field :id, {:size => 8} %>
  </p>
  <p>
    <%= f.label :full_api_key %><br />
    <%= f.text_field :full_api_key, {:size => 65} %>
  </p>
  <p>
    <%= f.submit 'Add' %> | 
    <%= link_to 'Cancel', home_path %>
  </p>
  <p>
    You can find your Eve API keys at 
    <%= link_to "http://www.eveonline.com/api/default.asp", "http://www.eveonline.com/api/default.asp" %>.
  </p>
<% end %>

app/views/accounts/show.html.erb
<p>
  <b>Id:</b>
  <%=h @account.id %>
</p>

<p>
  <b>Full api key:</b>
  <%=h @account.full_api_key %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>